# Site Info
title: starfishkenny's Ocean
tagline: "starfishkenny's Ocean"
description: "Let's Dive In"
baseurl: ""
url: http://starfishkenny.github.io
logo: '/public/logo.png'

# Site configurations
gems:
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss    
paginate: 5
paginate_path: '/blog/page:num'
permalink: pretty

version: 1.0.0

# About/contact
author:
  name: YOUNGYOO KIM
  description: Kenny (YOUNGYOO KIM)
  contact:
    linkedin:  https://www.linkedin.com/in/youngyoo-kim-8a1ba017b/
    github:    https://github.com/starfishkenny
    # facebook:  <hide>
    # twitter:   <hide>
    # weibo:     <hide>
    email:     mailto:youngyoo.kim.94@gmail.com

# Navigation (2nd level links supported)
nav:
  Home:           
    - '/blog/'
  Today I Learned:           
    - '/'
    - { Categories: '/blog/categories/' }
    # - { Tags: '/blog/tags/' }
    - { Github Pages: '/blog/categories/#Github_Pages'}
    - { Git: '/blog/categories/#Git'}
  About:          
    - '/about/'
  Search:          
    - '/search/'

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'

hero:
  image: /public/img/european_subway.jpg
  caption: Photo By &copy; starfishkenny</a>

# Puglins
mathjax: true # whether support mathjax
google_analytics_token: '' # leave blank if you don't want google analytics
disqus_short_name: '' # leave blank if you don't want disqus

