# Site Info
title: starfishkenny's Ocean
tagline: "starfishkenny's Ocean"
description: "Share knowledge and benefit everyone"
baseurl: ""
url: https://starfishkenny.github.io
logo: '/public/logo.png'

# Site configurations
gems:
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss    
paginate: 5
paginate_path: '/blog/page:num'
permalink: pretty

version: 1.0.0

# About/contact
author:
  name: YOUNGYOO KIM
  description: starfishkenny (YOUNGYOO KIM)
               Studying & Learning Everyday
  contact:
    linkedin:  https://www.linkedin.com/in/youngyoo-kim-8a1ba017b/
    github:    https://github.com/starfishkenny
    # facebook:  <hide>
    # twitter:   <hide>
    # weibo:     <hide>
    email:     mailto:youngyoo.kim.94@gmail.com

# Navigation (2nd level links supported)
nav:
  Home:           
    - '/'
  Categories:           
    - '/blog/categories/'
    # - { Tags: '/blog/tags/' }
    # - { Let's Dive In: "/blog/categories/#Let's Dive In" }
    # - { Github Pages: '/blog/categories/#Github_Pages'}
  Tags:
    - '/blog/tags/'
  Search:          
    - '/search/'
  About:          
    - '/about/'


# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'

hero:
  image: /public/img/european_sea.jpg
  caption: Lisboa, Portugal (Photo By &copy; starfishkenny)

# Puglins
mathjax: true # whether support mathjax
google_analytics_token: 'G-JXQFJMCXGS' # leave blank if you don't want google analytics
disqus_short_name: 'starfishkenny' # leave blank if you don't want disqus